stages:
  - test
  - notify

.molecule_base:
  stage: test
  tags:
    - proxmox-docker
  image: docker-picodata.binary.picodata.io/ansible-proxmox:latest
  script:
    - molecule converge -s "$MOLECULE_SCENARIO" -- -e "package_with_version=picodata=$PICODATA_VERSION"

molecule:
  extends: .molecule_base
  parallel:
    matrix:
    matrix:
      - PICODATA_VERSION: 25.2.2.0-noble
        MOLECULE_SCENARIO:
          - systemd
          - rootless
          - supervisord
      - PICODATA_VERSION: 25.5.9.0-noble
        MOLECULE_SCENARIO:
          - systemd
          - rootless
          - supervisord
      - PICODATA_VERSION: 26.1.4.0-noble
        MOLECULE_SCENARIO:
          - systemd
          - rootless
          - supervisord

release:
  stage: notify
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
  variables:
    PARENT_PROJECT_NAME: $CI_PROJECT_NAME
    PARENT_VERSION: $CI_COMMIT_TAG
    PARENT_PROJECT_ID: $CI_PROJECT_ID
  inherit:
    variables: false
  trigger:
    project: picodata/devops/builder-ansible
    strategy: mirror
