workflow:
  # See https://docs.gitlab.com/ee/ci/jobs/job_control.html#avoid-duplicate-pipelines
  rules:
    # To avoid duplicate pipelines we disable merge request events,
    # leaving only pushes and manual triggering.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/

stages:
  - notify

release:
  stage: notify
  variables:
    PARENT_PROJECT_NAME: $CI_PROJECT_NAME
    PARENT_VERSION: $CI_COMMIT_TAG
    PARENT_PROJECT_ID: $CI_PROJECT_ID
  inherit:
    variables: false
  trigger:
    project: picodata/devops/builder-ansible
    strategy: mirror


