spec:
  inputs:
    picodata_version:
      default: "picodata=26.1.6.0-noble"
      description: "Версия Picodata для тестирования **(имя пакета ТОЛЬКО под Ubuntu Noble!!!)**"
    picodata_repo:
      default: "https://download.picodata.io"
      description: "Репозиторий для установки пакетов"
      type: string
      options:
        - "https://download.picodata.io"
        - "https://download.binary.picodata.io"
---
stages:
  - test
  - notify

.molecule_base:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_COMMIT_TAG
      when: never    
  tags:
    - proxmox-docker
  image: docker-picodata.binary.picodata.io/ansible-proxmox:latest
  variables:
    JOB_SUFFIX: "$CI_CONCURRENT_PROJECT_ID"
  retry: 1
  script:
    - |
      if echo "$PICODATA_VERSION" | grep "25.2.2.0" ; then PLUGIN_NAME=$PLUGIN_NAME252; else PLUGIN_NAME=$PLUGIN_NAME25; fi
      export PLUGIN_NAME
    - env | grep -i picodata
    - |
      if [ "$PICODATA_VERSION" != "" ]; then
        molecule converge -s "$MOLECULE_SCENARIO" -- -e "package_with_version=$PICODATA_VERSION"
      else
        molecule converge -s "$MOLECULE_SCENARIO"
      fi

molecule:
  extends: .molecule_base
  parallel:
    matrix:
      - PICODATA_VERSION:
        - picodata=25.2.2.0-noble
        - picodata=25.5.10.0-noble
        - picodata=26.1.6.0-noble
        PLUGIN_NAME252: weather_cache_0.1.0-ubuntu_24.04.tar.gz          
        PLUGIN_NAME25: weather_cache_0.2.0-ubuntu_24.04.tar.gz
        ANSIBLE_PYTHON: /usr/bin/python3
        CONTAINER_TEMPLATE: ubuntu-24.04-standard_24.04-2_amd64.tar.zst
        MOLECULE_SCENARIO:
          - systemd
          - rootless
          - supervisord

      - PICODATA_VERSION:
        - picodata=25.5.10.0-resolute
        - picodata=26.1.6.0-resolute
        PLUGIN_NAME25: weather_cache_0.2.1-ubuntu_26.04.tar.gz
        CONTAINER_TEMPLATE: ubuntu-26.04-standard_26.04-1_amd64.tar.zst
        ANSIBLE_PYTHON: /usr/bin/python3
        MOLECULE_SCENARIO:
          - systemd
          - rootless
          - supervisord

      - PICODATA_VERSION: 
        - picodata-25.2.2.0
        - picodata-25.5.10.0
        - picodata-26.1.6.0
        CONTAINER_TEMPLATE: rockylinux-8-cloud_20240408_amd64.tar.xz
        PLUGIN_NAME252: weather_cache_0.1.0-centos_8.tar.gz
        PLUGIN_NAME25: weather_cache_0.2.1-centos_8.tar.gz
        ANSIBLE_PYTHON: /usr/libexec/platform-python
        MOLECULE_SCENARIO:
          - systemd
          - rootless
          - supervisord

      - PICODATA_VERSION: 
        - picodata-25.2.2.0
        - picodata-25.5.10.0
        - picodata-26.1.6.0
        CONTAINER_TEMPLATE: almalinux-9-default_20240911_amd64.tar.xz
        PLUGIN_NAME252: weather_cache_0.1.0-centos_9.tar.gz
        PLUGIN_NAME25: weather_cache_0.2.1-centos_9.tar.gz
        ANSIBLE_PYTHON: /usr/bin/python3
        OS: "centos9"
        MOLECULE_SCENARIO:
          - systemd
          - rootless
          - supervisord

      - PICODATA_VERSION: 
        - picodata=25.2.2.0-bullseye
        - picodata=25.5.10.0-bullseye
        - picodata=26.1.6.0-bullseye
        CONTAINER_TEMPLATE: debian-11-standard_11.7-1_amd64.tar.zst
        PLUGIN_NAME252: weather_cache_0.1.0-debian_11.tar.gz
        PLUGIN_NAME25: weather_cache_0.2.1-debian_11.tar.gz
        ANSIBLE_PYTHON: /usr/bin/python3
        MOLECULE_SCENARIO:
          - systemd
          - rootless
          - supervisord

      - PICODATA_VERSION: 
        - picodata=25.5.10.0-trixie
        - picodata=26.1.6.0-trixie
        CONTAINER_TEMPLATE: debian-13-standard_13.6-1_amd64.tar.zst
        PLUGIN_NAME25: weather_cache_0.2.1-debian_13.tar.gz
        ANSIBLE_PYTHON: /usr/bin/python3
        MOLECULE_SCENARIO:
          - systemd
          - rootless
          - supervisord

      - PICODATA_VERSION: 
        - picodata=25.2.2.0-1.p9
        - picodata=25.5.10.0-1.p9
        - picodata=26.1.6.0-1.p9
        CONTAINER_TEMPLATE: alt-p9-cloud_20240408_amd64.tar.xz
        PLUGIN_NAME252: weather_cache_0.1.0-altlinux_p9.tar.gz
        PLUGIN_NAME25: weather_cache_0.2.1-altlinux_p9.tar.gz
        ANSIBLE_PYTHON: /usr/bin/python3
        OS: "altlinux"
        MOLECULE_SCENARIO:
          - systemd
          - rootless
          - supervisord

      - PICODATA_VERSION: 
        - picodata=25.2.2.0-1.p10
        - picodata=25.5.10.0-1.p10
        - picodata=26.1.6.0-1.p10
        CONTAINER_TEMPLATE: alt-p10-cloud_20240408_amd64.tar.xz
        PLUGIN_NAME252: weather_cache_0.1.0-altlinux_p10.tar.gz
        PLUGIN_NAME25: weather_cache_0.2.1-altlinux_p10.tar.gz
        ANSIBLE_PYTHON: /usr/bin/python3
        OS: "altlinux"
        MOLECULE_SCENARIO:
          - systemd
          - rootless
          - supervisord


manual:
  extends: .molecule_base
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: on_success
  variables:
    PICODATA_REPO: "$[[ inputs.picodata_repo ]]"
  needs: []
  parallel:
    matrix:
      - PICODATA_VERSION: "$[[ inputs.picodata_version ]]"
        PLUGIN_NAME25: weather_cache_0.2.0-ubuntu_24.04.tar.gz
        CONTAINER_TEMPLATE: ubuntu-24.04-standard_24.04-2_amd64.tar.zst
        ANSIBLE_PYTHON: /usr/bin/python3
        MOLECULE_SCENARIO:
          - systemd
          - rootless
          - supervisord

release:
  stage: notify
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/
  variables:
    PARENT_PROJECT_NAME: $CI_PROJECT_NAME
    PARENT_VERSION: $CI_COMMIT_TAG
    PARENT_PROJECT_ID: $CI_PROJECT_ID
  inherit:
    variables: false
  trigger:
    project: picodata/devops/builder-ansible
    strategy: mirror
