---
# tasks for backup

- name: Copy utility files on remote hosts
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '{{ ansible_user_dir }}'
    mode: '0755'
  loop:
    - backup.sh

- name: Generate list of instances per server
  ansible.builtin.import_tasks:
    file: genin.yml

- name: Set current time
  ansible.builtin.set_fact:
    DT: '{{ "%Y%m%d%H%M%S" | strftime }}'

- name: Backup instances
  ansible.builtin.command:
    cmd: '{{ ansible_user_dir }}/backup.sh -s {{ run_dir }}/{{ cluster_id }}/{{ instance }}.sock -d {{ backup_dir }}/{{ DT }}'
  loop: '{{ instances_on_host }}'
  loop_control:
    loop_var: instance

- block:
  - name: Pack backups for fetch
    ansible.builtin.shell:
      chdir: '{{ backup_dir }}/{{ DT }}'
      cmd: 'tar -cf {{ backup_dir }}/{{ inventory_hostname }}.tar *'

  - name: Fetch backups from remote hosts
    ansible.builtin.fetch:
      src: '{{ backup_dir }}/{{ inventory_hostname }}.tar'
      dest: '{{ backup_fetch_dir }}/{{ cluster_id }}/{{ DT }}/{{ inventory_hostname }}.tar'
      flat: true

  - name: Remove archive on remote hosts
    ansible.builtin.file:
      path: '{{ backup_dir }}/{{ inventory_hostname }}.tar'
      state: absent

  when: backup_fetch == True
# end block

- name: Remove utility files on remote hosts
  ansible.builtin.file:
    path: '{{ ansible_user_dir }}/{{ item }}'
    state: absent
  loop:
    - backup.sh
