---
# tasks for execute lua command on instances

- name: ({{ cluster_name }}) Generate list of instances per server
  ansible.builtin.import_tasks:
    file: genin.yml

- block:

  - name: ({{ cluster_name }}) Debug cmdline
    ansible.builtin.debug:
      var: cmdline
    run_once: true
    when: debug == true

  - name: ({{ cluster_name }}) Create temporary file
    ansible.builtin.tempfile:
      path: '{{ data_dir }}/{{ cluster_name }}'
      state: file
      suffix: picocmd
    register: tempfile

  - name: ({{ cluster_name }}) Debug tempfile
    ansible.builtin.debug:
      var: tempfile
    run_once: true
    when: debug == true

  - name: ({{ cluster_name }}) Generate command file
    ansible.builtin.copy:
      content: |
        {{ cmdline }}
      dest: '{{ tempfile.path }}'
      owner: '{{ user }}'
      group: '{{ group }}'
      mode: '0644'

  - name: ({{ cluster_name }}) Set name of command file
    ansible.builtin.set_fact:
      cmdfile: '{{ tempfile.path }}'

  when: cmdline is defined

- block:
  - name: ({{ cluster_name }}) Get name of command file
    ansible.builtin.set_fact:
      cmdfile_name: '{{ cmdfile | basename  }}'

  - name: ({{ cluster_name }}) Debug cmdfile_name
    ansible.builtin.debug:
      var: cmdfile_name
    run_once: true

  - name: ({{ cluster_name }}) Copy command file to hosts
    ansible.builtin.copy:
      src: '{{ cmdfile }}'
      dest: '{{ data_dir }}/{{ cluster_name }}'
      owner: '{{ user }}'
      group: '{{ group }}'
      mode: '0644'
    when: tempfile.path is undefined

  - name: ({{ cluster_name }}) Set filter on instances
    ansible.builtin.set_fact:
      instances_filtered: '{{ list_instance_names | select ("ansible.builtin.search", filter | default(".*")) | list }}'

  - name: ({{ cluster_name }}) Debug instances_on_host
    ansible.builtin.debug:
      var: instances_on_host
    run_once: true

  - name: ({{ cluster_name }}) Debug instances_filtered
    ansible.builtin.debug:
      var: instances_filtered
    run_once: true

  - name: ({{ cluster_name }}) Execute file with commands
    ansible.builtin.shell:
      cmd: >
          echo "Host: {{ inventory_hostname }}";
          echo "Instance: {{ instance }}";
          (echo "\lua"; cat "{{ data_dir }}/{{ cluster_name }}/{{ cmdfile_name }}")
          | {{ bin_dir }}/picodata admin --ignore-errors {{ run_dir }}/{{ cluster_name }}/{{ instance }}.sock
    loop: '{{ instances_filtered }}'
    loop_control:
      loop_var: instance
    register: result
    ignore_errors: true

  - name: ({{ cluster_name }}) Remove command file on hosts
    ansible.builtin.file:
      path: '{{ data_dir }}/{{ cluster_name }}/{{ cmdfile_name }}'
      state: absent

  - name: ({{ cluster_name }}) Debug result from one host
    ansible.builtin.debug:
      var: result
    run_once: true
    when: debug == true

  - name: ({{ cluster_name }}) Debug ansible_play_hosts
    ansible.builtin.debug:
      var: ansible_play_hosts
    run_once: true
    when: debug == true

  - name: ({{ cluster_name }}) Save sqlline result to local file
    become: false
    ansible.builtin.copy:
      content: |
        {% for host in ansible_play_hosts | sort %}
        {{ hostvars[host].result.results | map(attribute="stdout_lines") | list | to_nice_json }}
        {% endfor %}
      dest: '{{ report_dir }}/command_result_{{ "%Y%m%d%H%M%S" | strftime }}.log'
      mode: 0644
    delegate_to: localhost
    run_once: true

  when: cmdfile is defined
