- name: Print topology
  ansible.builtin.debug:
    msg: "Id: {{ item.key }} Count: {{ item.value.instances_per_server }} Replication factor: {{item.value.replication_factor | default('1')}}"
  loop: "{{ lookup('ansible.builtin.dict', tiers, wantlist=True) }}"
  run_once: true

- name: Check picodata is installed
  ansible.builtin.command:
    cmd: 'picodata --version'
  register: result
  ignore_errors: true

- name: Set flag for install picodata needed
  ansible.builtin.set_fact:
    install_packages: true
  when: result.rc != 0

- name: Install picodata packages
  ansible.builtin.import_tasks:
    file: install_packages.yml
  when: install_packages

- name: Create dirs
  ansible.builtin.file:
    name: '{{ item }}'
    state: directory
    owner: '{{ user }}'
    group: '{{ group }}'
  loop:
    - '{{ conf_dir }}/{{ cluster_id }}'
    - '{{ log_dir }}/{{ cluster_id }}'

- name: Set failure domain
  ansible.builtin.set_fact:
    fd: 'DC={{ group_names }},HOST={{ inventory_hostname }}'
  when: not fd_uniq_per_instance

- name: Debug failure domain
  ansible.builtin.debug:
    msg: 'fd is {{ fd }}'
  when: not fd_uniq_per_instance

- name: Set server failure domain
  ansible.builtin.set_fact:
    target_hosts: "none"
  when: target_hosts is undefined

- name: Set peer instance
  ansible.builtin.set_fact:
    main_peer: '{{ listen_ip }}'
  run_once: true
  when: main_peer is undefined

- name: Debug main_peer
  ansible.builtin.debug:
    msg: 'main_peer is {{ main_peer }}'
  run_once: true

- name: Generate tier file
  ansible.builtin.template:
    src: tiers-conf.j2
    dest: '{{ conf_dir }}/{{ cluster_id }}/tiers.conf'
    force: true

- name: Generate template for units
  ansible.builtin.template:
    src: systemd-unit-service.j2
    dest: '{{ systemd_dir }}/{{ cluster_id }}@.service'
    force: true

- name: Init instance number on server
  ansible.builtin.set_fact:
    instance_num: 0

- name: Tiers setup
  ansible.builtin.include_tasks:
    file: tiers_setup.yml
  loop: "{{ lookup('ansible.builtin.dict', tiers, wantlist=True) }}"
  loop_control:
    loop_var: tier
    extended: true