---
# tasks file for picodata-ansible

- name: Deploy picodata
  ansible.builtin.import_tasks:
    file: deploy.yml
  tags: [ deploy, restore_full ]

- name: Install picodata packages
  ansible.builtin.import_tasks:
    file: install_packages.yml
  tags: [ never, install_pkgs ]

- name: Remove picodata
  ansible.builtin.import_tasks:
    file: remove.yml
  tags: [ never, remove ]

- name: Backup picodata
  ansible.builtin.import_tasks:
    file: backup.yml
  tags: [ never, backup ]

- name: Restore picodata
  ansible.builtin.import_tasks:
    file: restore.yml
  tags: [ never, restore, restore_full ]

- name: Generate inventory
  ansible.builtin.import_tasks:
    file: genin.yml
  tags: [ never, genin ]
