---
# tasks file for picodata-ansible

- name: Install picodata
  ansible.builtin.include_tasks:
    file: install.yml
  when: not force_remove

- name: Remove picodata
  ansible.builtin.include_tasks:
    file: remove.yml
  when: force_remove
