---
# tasks file for picodata-ansible

- block:
  - name: ({{ cluster_name }}) Set scope for systemd
    ansible.builtin.set_fact:
      systemd_scope: 'user'
      systemd_user: '{{ user }}'
      systemd_dir: '~/.config/systemd/user/'
    run_once: true
    when: rootless == true and init_system == 'systemd'

  - name: ({{ cluster_name }}) Register uid of {{ systemd_user }}
    command: 'id -u {{ systemd_user }}'
    register: uid
    changed_when: false

  - name: ({{ cluster_name }}) Debug uid
    ansible.builtin.debug:
      var: uid
    run_once: true
    when: debug == true

  - name: ({{ cluster_name }}) Set server failure domain
    ansible.builtin.set_fact:
      host_group: "none"
    when: host_group is undefined

  - name: ({{ cluster_name }}) Set all host groups for servers
    ansible.builtin.set_fact:
      all_host_groups: "{{ all_host_groups|default([])  + [ hostvars[item]['host_group']|default([]) ]  }}"
    loop: "{{ groups['all'] }}"
    run_once: true

  - name: ({{ cluster_name }}) Init variables
    ansible.builtin.set_fact:
      all_hosts: '{{ groups["all"] }}'
      tag: ''

  - name: ({{ cluster_name }}) Debug all_hosts
    ansible.builtin.debug:
      var: all_hosts
    when: debug == true

  tags: [ always ]
# end block

- name: ({{ cluster_name }}) Deploy Picodata cluster
  ansible.builtin.import_tasks:
    file: deploy.yml
  tags: [ deploy, restore_full ]

- name: ({{ cluster_name }}) Install Picodata packages for Picodata cluster
  ansible.builtin.import_tasks:
    file: install_packages.yml
  tags: [ never, install_pkgs ]

- name: ({{ cluster_name }}) Remove Picodata cluster
  ansible.builtin.import_tasks:
    file: remove.yml
  tags: [ never, remove ]

- name: ({{ cluster_name }}) Restart Picodata cluster
  ansible.builtin.import_tasks:
    file: restart.yml
  tags: [ never, restart ]

- name: ({{ cluster_name }}) Stop Picodata cluster
  ansible.builtin.import_tasks:
    file: stop.yml
  tags: [ never, stop ]

- name: ({{ cluster_name }}) Start Picodata cluster
  ansible.builtin.import_tasks:
    file: start.yml
  tags: [ never, start ]

- name: ({{ cluster_name }}) Backup Picodata cluster
  ansible.builtin.import_tasks:
    file: backup.yml
  tags: [ never, backup ]

- name: ({{ cluster_name }}) Restore Picodata cluster
  ansible.builtin.import_tasks:
    file: restore.yml
  tags: [ never, restore, restore_full ]

- name: ({{ cluster_name }}) Generate inventory for Picodata cluster
  ansible.builtin.import_tasks:
    file: genin.yml
  tags: [ never, genin ]

- name: ({{ cluster_name }}) Install plugins into Picodata cluster
  ansible.builtin.import_tasks:
    file: plugins.yml
  tags: [ never, plugins, plugin ]

- name: ({{ cluster_name }}) Deploy Picodata cluster (for become with rootless)
  ansible.builtin.import_tasks:
    file: deploy_become.yml
  tags: [ never, deploy_become ]

- name: ({{ cluster_name }}) Remove root files after remove (for become with rootless)
  ansible.builtin.import_tasks:
    file: remove_become.yml
  tags: [ never, remove_become ]

- name: ({{ cluster_name }}) Get crashed dumpfiles of Picodata cluster
  ansible.builtin.import_tasks:
    file: crash_dump.yml
  tags: [ never, crash_dump ]

- name: ({{ cluster_name }}) Execute command on Picodata cluster
  ansible.builtin.import_tasks:
    file: command.yml
  tags: [ never, command ]

- name: Make links on instances
  ansible.builtin.import_tasks:
    file: make_links.yml
  tags: [ never, make_links ]

- name: Rebootstrap of one instance
  ansible.builtin.import_tasks:
    file: rebootstrap.yml
  tags: [ never, rebootstrap ]

- name: Create report files
  ansible.builtin.import_tasks:
    file: report.yml
  tags: [ never, report ]

- name: Expand cluster
  ansible.builtin.import_tasks:
    file: expand.yml
  tags: [ never, expand ]
