---
# tasks for execute lua command on instances

- name: ({{ cluster_name }}) Generate list of instances per server
  ansible.builtin.include_tasks:
    file: genin.yml
  when: not instances_on_host | default([])

- name: ({{ cluster_name }}) Set init variables
  ansible.builtin.set_fact:
    start_num: 1
    instance_link_new: []

- name: ({{ cluster_name }}) Set start number if expanded
  ansible.builtin.set_fact:
    start_num: '{{ real_cnt | int + 1 }}'
  when: tag == 'expand'

- name: ({{ cluster_name }}) Print start_num
  ansible.builtin.debug:
    var: start_num
  when: debug == true

- name: ({{ cluster_name }}) Get information from service tables
  ansible.builtin.shell:
    cmd: >
         echo "
         SELECT *
         FROM ( SELECT i.name, p.address, substring(p.address, ':(.*)')::INT {% if filename_format != 'binport' %} - {{ first_bin_port }} + 1{% endif %} as num
                FROM _pico_instance AS i
                JOIN _pico_peer_address AS p ON i.raft_id=p.raft_id
                WHERE connection_type='iproto' and substring(p.address, '(.*):.*') = '{{ listen_address }}' )
         WHERE num>={{ start_num }}{% if filename_format == 'binport' %} + {{ first_bin_port }} - 1{% endif %}" |
         {{ bin_dir }}/picodata admin {{ run_dir }}/{{ cluster_name }}/{{ instances_on_host[0] }}.sock  |
         grep '|' | grep -v '+-' | grep -Ev 'name.* | address' | tr -d ' ' | cut -f 2-4 -d '|' | tr '|' ','
  register: result_sql
  changed_when: false

- name: ({{ cluster_name }}) Print result_sql
  ansible.builtin.debug:
    var: result_sql
  when: debug == true

- name: ({{ cluster_name }}) Set instance_name list for ansible version before 2.11
  ansible.builtin.set_fact:
    instance_name_list: "[{% for l in result_sql.stdout_lines %}{{ l | regex_search('(.*),(.*),(.*)', '\\1', '\\2', '\\3') | list }},{% endfor %}]"
  when: ansible_version.full is version('2.11', '<')

- name: ({{ cluster_name }}) Set instance_name list for ansible version 2.11 and later
  ansible.builtin.set_fact:
    instance_name_list: "{{ result_sql.stdout_lines | map('split', ',') | list }}"
  when: ansible_version.full is version('2.11', '>=')

- name: ({{ cluster_name }}) Print instance_name_list
  ansible.builtin.debug:
    var: instance_name_list
  when: debug == true

- name: ({{ cluster_name }}) Set instance links
  ansible.builtin.set_fact:
    instance_link_new: "{{ instance_link_new | default([]) + [[ item.0 , '%03d' | format(item.2|int) ]] }}"
  loop: '{{ instance_name_list }}'
  loop_control:
    extended: true

- name: ({{ cluster_name }}) Print list_instance_names
  ansible.builtin.debug:
    msg: "{{ list_instance_names }}"
  when: debug == true

- name: ({{ cluster_name }}) Print instance_link_new
  ansible.builtin.debug:
    msg: "{{ instance_link_new }}"
  when: debug == true

- name: ({{ cluster_name }}) Set list_instance_names for default
  ansible.builtin.set_fact:
    list_instance_names: "{{ instance_link_new | map(attribute='0') | list }}"
  when: start_num|int == 1

- name: ({{ cluster_name }}) Set list_instance_names when expand
  ansible.builtin.set_fact:
    list_instance_names: "{{ list_instance_names + instance_link_new | map(attribute='0') | list }}"
  when: start_num|int > 1

- name: Processing for create_links
  block:

  - name: ({{ cluster_name }}) Clean all links
    ansible.builtin.command:
      cmd: 'find "{{ item }}" -maxdepth 1 -type l -delete'
    loop:
      - '{{ data_dir }}/{{ cluster_name }}'
      - '{{ conf_dir }}/{{ cluster_name }}'
      - '{{ run_dir }}/{{ cluster_name }}'
      - '{{ log_dir }}/{{ cluster_name }}'
    when: start_num|int == 1

  - name: ({{ cluster_name }}) Clean aliases for systemd
    ansible.builtin.command:
      cmd: 'find "{{ systemd_dir }}" -maxdepth 1 -name "{{ cluster_name }}-*.service" -type l -delete'
    when: init_system == 'systemd' and start_num == 1

  - name: ({{ cluster_name }}) Make links on data
    ansible.builtin.command:
      chdir: '{{ data_dir }}/{{ cluster_name }}'
      cmd: 'ln -f -s {{ instance[1] | basename }} {{ instance[0] }}'
    loop: '{{ instance_link_new }}'
    loop_control:
      loop_var: instance
    notify:
      - refactor

  - name: ({{ cluster_name }}) Make links on conf
    ansible.builtin.command:
      chdir: '{{ conf_dir }}/{{ cluster_name }}'
      cmd: 'ln -f -s {{ instance[1] | basename }}.conf {{ instance[0] }}.conf'
    loop: '{{ instance_link_new }}'
    loop_control:
      loop_var: instance

  - name: ({{ cluster_name }}) Make links on sock
    ansible.builtin.command:
      chdir: '{{ run_dir }}/{{ cluster_name }}'
      cmd: 'ln -f -s {{ instance[1] | basename }}.sock {{ instance[0] }}.sock'
    loop: '{{ instance_link_new }}'
    loop_control:
      loop_var: instance

  - name: ({{ cluster_name }}) Make links on log
    ansible.builtin.command:
      chdir: '{{ log_dir }}/{{ cluster_name }}'
      cmd: 'ln -f -s {{ instance[1] | basename }}.log {{ instance[0] }}.log'
    loop: '{{ instance_link_new }}'
    loop_control:
      loop_var: instance
    when: log_to == 'file'

  - name: ({{ cluster_name }}) Make links on audit
    ansible.builtin.command:
      chdir: '{{ log_dir }}/{{ cluster_name }}'
      cmd: 'ln -f -s audit-{{ instance[1] | basename }}.log audit-{{ instance[0] }}.log'
    loop: '{{ instance_link_new }}'
    loop_control:
      loop_var: instance
    when: audit == True and audit_to == 'file'

  - name: ({{ cluster_name }}) Patch instance name in config file
    ansible.builtin.replace:
      path: '{{ conf_dir }}/{{ cluster_name }}/{{ instance[1] | basename }}.conf'
      regexp: "^#  name: '.*'$"
      replace: "#  name: '{{ instance[0] }}'"
      after: 'instance:'
      before: '  peer: .*'
    loop: '{{ instance_link_new }}'
    loop_control:
      loop_var: instance

  # for systemd
  - name: Processing for systemd
    block:

    - name: ({{ cluster_name }}) Make links on systemd unit (alias)
      ansible.builtin.command:
        chdir: '{{ systemd_dir }}'
        cmd: 'ln -f -s {{ cluster_name }}-{{ instance[1] | basename }}.service {{ cluster_name }}-{{ instance[0] }}.service'
      loop: '{{ instance_link_new }}'
      loop_control:
        loop_var: instance

    - name: ({{ cluster_name }}) Reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
        scope: '{{ systemd_scope }}'
      environment:
        XDG_RUNTIME_DIR: /run/user/{{uid.stdout}}

    when: init_system == 'systemd'
  # end block

  when: create_links == true
# end block
