---
# tasks for plugins

- name: Generate list of instances per server
  ansible.builtin.include_tasks:
    file: genin.yml
  when: instances_on_host is undefined

- name: Create dir for plugins
  ansible.builtin.file:
    name: '{{ data_dir }}/{{ cluster_name }}/plugins'
    state: directory

- name: Plugins setup
  ansible.builtin.include_tasks:
    file: plugins_setup.yml
  loop: "{{ lookup('ansible.builtin.dict', plugins | default({}), wantlist=True) }}"
  loop_control:
    loop_var: plugin
    extended: true
