---
# tasks for plugins

- name: Generate list of instances per server
  ansible.builtin.include_tasks:
    file: genin.yml
  when: instances_on_host is undefined

- name: Set dir for plugins
  ansible.builtin.set_fact:
    plugins_dir: '{{ share_dir }}/{{ cluster_name }}'
  run_once: true

- name: Create dir for plugins
  ansible.builtin.file:
    name: '{{ plugins_dir }}'
    state: directory

- name: Plugins setup
  ansible.builtin.include_tasks:
    file: plugins_setup.yml
  loop: "{{ lookup('ansible.builtin.dict', plugins | default({}), wantlist=True) }}"
  loop_control:
    loop_var: plugin
    extended: true
