---
- block:

  - block:
    - name: Disable systemd service for supervisord
      ansible.builtin.systemd:
        name: 'supervisord-{{ cluster_name }}.service'
        enabled: false
        state: stopped
      ignore_errors: True

    - name: Remove supervisord configs
      ansible.builtin.file:
        name: '{{ supervisord_dir }}/{{ cluster_name }}.conf'
        state: absent

    when: init_system == 'supervisord' and systemd_scope == 'system'
  # end block

  - name: Remove logrotate file
    ansible.builtin.file:
      name: '/etc/logrotate.d/picodata-{{ cluster_name }}'
      state: absent
    when: log_to == 'file'

  - name: Remove dirs
    ansible.builtin.file:
      name: '{{ item }}'
      state: absent
    loop:
      - '{{ conf_dir }}'
      - '{{ log_dir }}'
      - '{{ data_dir }}'
      - '{{ run_dir }}'
      - '{{ share_dir }}'
      - '{{ cert_dir }}'
      - '{{ systemd_dir }}/supervisord-{{ cluster_name }}.service'
      - '/etc/tmpfiles.d/picodata.conf'
    ignore_errors: True

  become: true
# end block

