---
# tasks for create report files

# Set variables for work
- name: ({{ cluster_name }}) Generate list of instances per server
  ansible.builtin.include_tasks:
    file: genin.yml

- block:
  - name: Set flag for block create links
    ansible.builtin.set_fact:
      create_links: false

  - name: ({{ cluster_name }}) Generate list of instances per server
    ansible.builtin.include_tasks:
      file: make_links.yml
  when: autonames|bool == true

- name: ({{ cluster_name }}) Set flag for create report files
  command: 'true'
  notify:
    - refactor
