---
# tasks for create report files

# Set variables for work
- name: ({{ cluster_name }}) Generate list of instances per server
  ansible.builtin.include_tasks:
    file: genin.yml

- name: ({{ cluster_name }}) Set flag for create report files
  command: 'true'
  notify:
    - refactor
