---
# tasks for restart cluster

- name: Set server failure domain
  ansible.builtin.set_fact:
    host_group: "none"
  when: host_group is undefined

- name: Generate list of instances per server
  ansible.builtin.include_tasks:
    file: genin.yml
  when: instances_on_host is undefined

- name: Restart systemd units
  throttle: '{{ serial_host_restart | default(100) }}'
  ansible.builtin.service:
    name: '{{ cluster_name }}@{{ instance }}.service'
    state: restarted
  loop: '{{ instances_on_host }}'
  loop_control:
    loop_var: instance
  ignore_errors: True
  when: init_system == 'systemd'

- name: Restart supervisord processes
  throttle: '{{ serial_host_restart | default(100) }}'
  ansible.builtin.shell:
    cmd: /usr/bin/supervisorctl -c {{ supervisord_dir }}/{{ cluster_name }}.conf restart all
  when: init_system == 'supervisord'
