---

- block:

  - name: Set init-replication-factor
    ansible.builtin.set_fact:
      init_replication_factor: '{{ tier.value.replication_factor | default(1) }}'
    run_once: true

  - name: Create script file for instances in tier {{ tier.key }}
    ansible.builtin.template:
      src: instance-script.j2
      dest: '{{ conf_dir }}/{{ cluster_id }}/{{ tier.key }}.conf'
      force: true
    when: tier.value.memtx_memory is defined

  - name: Create env file for instances in tier {{ tier.key }}
    ansible.builtin.include_tasks:
      file: systemd_units.yml
    loop: "{{ range(1, tier.value.instances_per_server + 1) | list }}"

  when: target_hosts in tier.value.target_hosts | default(['none'])