---
# subtasks for deploy cluster

- name: ({{ cluster_name }}) Debug host_group for tier {{ tier.key }}
  debug:
    msg: "host_group = {{ host_group }}    tier.value.host_groups = {{ tier.value.host_groups | default(['none']) }}"
  when: debug == true

- block:
  - name: ({{ cluster_name }}) Set init variables for tier {{ tier.key }}
    ansible.builtin.set_fact:
      init_replication_factor: '{{ tier.value.replication_factor | default(1) }}'
      instances_per_server: '{{ dict_instances_per_server[tier.key] }}'
      start_num: 1

  - name: ({{ cluster_name }}) Set start number if expanded for tier {{ tier.key }}
    ansible.builtin.set_fact:
      start_num: '{{ dict_start_num[tier.key] }}'
    when: tag == 'expand'

  - name: ({{ cluster_name }}) Debug start_num and instances_per_server for tier {{ tier.key }}
    debug:
      msg: 'start_num = {{ start_num }}    instances_per_server = {{ instances_per_server }}   need_add_instances = {{ instances_per_server|int + 1 - start_num|int }}'
    when: debug == true

  - name: ({{ cluster_name }}) Check instances_per_server on shrink for tier {{ tier.key }}
    ansible.builtin.fail:
      msg: 'Ошибка! В настоящий момент picodata не может урезать кластер! Такая возможность появится в версии 26.2!'
    when: instances_per_server|int + 1 < start_num|int

  - name: ({{ cluster_name }}) Setup instances for tier {{ tier.key }}
    ansible.builtin.include_tasks:
      file: instances_setup.yml
    loop: "{{ range(start_num|int, instances_per_server|int + 1) | list }}"
    loop_control:
      loop_var: instance_id

  - name: ({{ cluster_name }}) Fill db_config_all with parameters for tier {{ tier.key }}
    ansible.builtin.set_fact:
      db_config_all: |
        {{ db_config_all }}
        {% for key, value in tier.value.db_config.items() %}
        alter system set "{{ key }}" = {{ value }} for tier {{ tier.key }};
        {% endfor %}
    when: tier.value.db_config is defined and tag != 'expand'

  when: host_group in tier.value.host_groups | default(['none']) or tier.value.host_groups is undefined
# end block
