---
# subtasks for deploy cluster

- block:

  - name: Set init-replication-factor for tier {{ tier.key }}
    ansible.builtin.set_fact:
      init_replication_factor: '{{ tier.value.replication_factor | default(1) }}'
    run_once: true

  - name: Create config file for tier {{ tier.key }}
    ansible.builtin.template:
      src: tiers-conf.j2
      dest: '{{ conf_dir }}/{{ cluster_id }}/{{ tier.key }}.conf'
      force: true
      owner: '{{ user }}'
      group: '{{ group }}'

  - name: Setup instances in tier {{ tier.key }}
    ansible.builtin.include_tasks:
      file: instances_setup.yml
    loop: "{{ range(1, tier.value.instances_per_server + 1) | list }}"
    loop_control:
      loop_var: instance_id

  when: host_group in tier.value.host_groups | default(['none']) or tier.value.host_groups is undefined