---
scenario:
  converge_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: molecule-lxc-rootless
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  playbooks:
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
    converge: converge.yml
    prepare: prepare.yml
    verify: verify.yml
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
    ssh_connection:
      pipelining: True
  inventory:
    host_vars:
      molecule-lxc-rootless:
        ansible_python_interpreter: /usr/bin/python3
        template: templates:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst
        vmid: 9001
        node: big2
        api_host: 10.5.1.15
        api_user: "${PROXMOX_API_USER}"
        api_password: "${PROXMOX_API_PASSWORD}"
    group_vars:
      all:
        cluster_name: 'molecule-rootless'
        sysadm_user: "sysadm"
        dbadm_user: "dbadm"
        user: picodata
        group: picodata
        rootless: true
