---
plugin_name: "weather_cache_0.2.0-ubuntu_24.04.tar.gz"
admin_password: 'Ft1hcz1HHHmv2C9qld9D4!'
service_password: "Ft1hcz1HHHmv2C9qld9D4"
auth_webui: false
audit: true
listen_address: '{{ ansible_default_ipv4.address }}'
fd_uniq_per_instance: true
debug: true
db_config:
  raft_wal_count_max: 102400
extra_vars:
  PICODATA_UNSAFE_DISABLE_PLUGIN_COMPATIBILITY_CHECK: 1
tiers:
  arbiter:
    replicaset_count: 1
    replication_factor: 1
    can_vote: true
  default:
    replicaset_count: 1
    replication_factor: 2
    can_vote: false
    config:
      memtx:
        memory: 64M
plugins:
  weather_cache:
    path: '../plugin/{{ plugin_name }}'
    services:
      weather_service:
