---
scenario:
  converge_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
dependency:
  name: galaxy
driver:
  name: default
platforms:
  - name: "molecule-lxc-${MOLECULE_SCENARIO}-${JOB_SUFFIX}"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
  playbooks:
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
    prepare: ../shared/prepare.yml
    converge: converge.yml
    verify: ../shared/verify.yml
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
    ssh_connection:
      pipelining: true
  inventory:
    host_vars:
      "molecule-lxc-${MOLECULE_SCENARIO}-${JOB_SUFFIX}":
        ansible_python_interpreter: "{{ lookup('env', 'ANSIBLE_PYTHON') | default('/usr/bin/python3', true) }}"
        template: "templates:vztmpl/${CONTAINER_TEMPLATE}"
        vmid: "{{ 9000 + (lookup('env', 'JOB_SUFFIX') | default(0, true) | int) }}"
        node: big2
        api_host: 10.5.1.15
        api_user: "${PROXMOX_API_USER}"
        api_password: "${PROXMOX_API_PASSWORD}"
        ansible_host: "{{ inventory_hostname }}"
        os: "{{ lookup('env', 'OS') }}"
    group_vars:
      all:
        cluster_name: 'molecule-${MOLECULE_SCENARIO}-${JOB_SUFFIX}'
