# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |v|
    v.memory = 2048
    v.cpus = 1
    v.qemu_use_session = false
  end

  config.vm.define :picodata1 do |master|
    master.vm.box = "generic/debian12"
    master.vm.hostname = "picodata1"
    master.vm.network :private_network, ip: "192.168.59.20"
    master.vm.provision :shell, privileged: false, inline: $commands_set
    master.vm.box_check_update = false
  end
end

ssh_pub_key = File.read(File.expand_path("~/.ssh/id_vbox.key.pub")).strip
$commands_set = <<-SHELL
echo "#{ssh_pub_key}" >> /home/vagrant/.ssh/authorized_keys
SHELL
